#Discussion
#Aphids population growth
We excluded all the herbivores,flying insects and ground-dwellers, and in the treatment H aphids population growth was hightest of all Treatments.
This was followed by the HGD ( herbivore  and ground-dwellers), HP(herbivores and flying insects), HBP(herbivores + birds + flying insects (ground-dwellers excluded)), O(herbivores + all enemies) and HPGD(herbivores + flying insects + ground-dwellers (birds excluded). 
                                                                                                                                                                                                             
                                                                                                                                                                                                             
                                                                                                                                                                                                             For date2, Aphids population growth  was highest in H, which is followed by HGD, HP, HPGD, HBP and O.
                                                                                                                                                                                                             
                                                                                                                                                                                                             #Discussion
                                                                                                                                                                                                             #Aphids population growth
                                                                                                                                                                                                             We excluded all the herbivores,flying insects and ground-dwellers, and in the treatment H aphids population growth was hightest of all Treatments.
                                                                                                                                                                                                             This was followed by the HGD ( herbivore  and ground-dwellers), HP(herbivores and flying insects), HBP(herbivores + birds + flying insects (ground-dwellers excluded)), O(herbivores + all enemies) and HPGD(herbivores + flying insects + ground-dwellers (birds excluded). 
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          For date2, Aphids population growth  was highest in H, which is followed by HGD, HP, HPGD, HBP and O.
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          For date3, aphids population growth was highest in H, this was followed by HGD, HP, HBP, O and HPGD. 
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          Overall, the treatment H, which include 
                                                                                                                                                                                                                                                                                                                                                                                                                          herbivores only (all enemies excluded), could reduce the aphids population growth most, and, aphids population growth was less in the date 3.
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          For % Seminatural habitat,  the more complex landscape is,  the higher aphids population they have, and in the sampling date3,  aphids population growth was stable, regardless  of % seminatural habitat.
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          Our plot data, effects of landscape complexity and natural enemy exclusion on average daily aphid population growth across three sampling dates (1–3), corresponds with the date from the article.
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          #Effects of treatment on Parasitism rate 
                                                                                                                                                                                                                                                                                                                                                                                                                          For parasitism rate, HPGD was highest, and which was followed by O, HBP, HP, HGD, and H at date 1.
                                                                                                                                                                                                                                                                                                                                                                                                                          At date 2, HP was highest, and which is followed by HBP, O and HPGD, HGD, and H.
                                                                                                                                                                                                                                                                                                                                                                                                                          At date 3,  HP was maximum and followed by HBP, HPGD, O HGD and H.
                                                                                                                                                                                                                                                                                                                                                                                                                          Among all, HP(herbivores + flying insects) was highest at all sampling dates.
                                                                                                                                                                                                                                                                                                                                                                                                                          In the treatment that we remove every enemies was not changed much in all sampling dates.
                                                                                                                                                                                                                                                                                                                                                                                                                          Our plot data, effects of treatment on PR, at date1 corresponded with the data from the article.
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          Our plot data, effects of landscape complexity and natural enemy exclusion on aphids parasitism rate across three sampling dates (1–3), corresponds with the date from the article.
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          #Discussion
                                                                                                                                                                                                                                                                                                                                                                                                                          #Aphids population growth
                                                                                                                                                                                                                                                                                                                                                                                                                          We excluded all the herbivores,flying insects and ground-dwellers, and in the treatment H aphids population growth was hightest of all Treatments.
                                                                                                                                                                                                                                                                                                                                                                                                                          This was followed by the HGD ( herbivore  and ground-dwellers), HP(herbivores and flying insects), HBP(herbivores + birds + flying insects (ground-dwellers excluded)), O(herbivores + all enemies) and HPGD(herbivores + flying insects + ground-dwellers (birds excluded). 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       For date2, Aphids population growth  was highest in H, which is followed by HGD, HP, HPGD, HBP and O.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       For date3, aphids population growth was highest in H, this was followed by HGD, HP, HBP, O and HPGD. 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Overall, the treatment H, which include 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       herbivores only (all enemies excluded), could reduce the aphids population growth most, and, aphids population growth was less in the date 3.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       For % Seminatural habitat,  the more complex landscape is,  the higher aphids population they have, and in the sampling date3,  aphids population growth was stable, regardless  of % seminatural habitat.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Our plot data, effects of landscape complexity and natural enemy exclusion on average daily aphid population growth across three sampling dates (1–3), corresponds with the date from the article.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       #Effects of treatment on Parasitism rate 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       For parasitism rate, HPGD was highest, and which was followed by O, HBP, HP, HGD, and H at date 1.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       At date 2, HP was highest, and which is followed by HBP, O and HPGD, HGD, and H.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       At date 3,  HP was maximum and followed by HBP, HPGD, O HGD and H.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Among all, HP(herbivores + flying insects) was highest at all sampling dates.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       In the treatment that we remove every enemies was not changed much in all sampling dates.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Our plot data, effects of treatment on PR, at date1 corresponded with the data from the article.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Our plot data, effects of landscape complexity and natural enemy exclusion on aphids parasitism rate across three sampling dates (1–3), corresponds with the date from the article.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       #Effects of treatment on Syrphid fraction
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       O was highest  and followed by HPGD, HP, HGD, HPGD and H, and at  date 3, there was and increase of syrphid fraction in all treatments except for treatment H.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Our plot data, effects of landscape complexity and natural enemy exclusion on syrphid fraction across three sampling dates (1–3), corresponds with the date from the article.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       #Effects of treatment on Syrphid fraction
                                                                                                                                                                                                                                                                                                                                                                                                                          O was highest  and followed by HPGD, HP, HGD, HPGD and H, and at  date 3, there was and increase of syrphid fraction in all treatments except for treatment H.
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          Our plot data, effects of landscape complexity and natural enemy exclusion on syrphid fraction across three sampling dates (1–3), corresponds with the date from the article.
                                                                                                                                                                                                                                                                                                                                                                                                                          For date3, aphids population growth was highest in H, this was followed by HGD, HP, HBP, O and HPGD. 
                                                                                                                                                                                                             
                                                                                                                                                                                                             Overall, the treatment H, which include 
                                                                                                                                                                                                             herbivores only (all enemies excluded), could reduce the aphids population growth most, and, aphids population growth was less in the date 3.
                                                                                                                                                                                                             
                                                                                                                                                                                                             
                                                                                                                                                                                                             For % Seminatural habitat,  the more complex landscape is,  the higher aphids population they have, and in the sampling date3,  aphids population growth was stable, regardless  of % seminatural habitat.
                                                                                                                                                                                                             
                                                                                                                                                                                                             Our plot data, effects of landscape complexity and natural enemy exclusion on average daily aphid population growth across three sampling dates (1–3), corresponds with the date from the article.
                                                                                                                                                                                                             
                                                                                                                                                                                                             
                                                                                                                                                                                                             #Discussion
                                                                                                                                                                                                             #Aphids population growth
                                                                                                                                                                                                             We excluded all the herbivores,flying insects and ground-dwellers, and in the treatment H aphids population growth was hightest of all Treatments.
                                                                                                                                                                                                             This was followed by the HGD ( herbivore  and ground-dwellers), HP(herbivores and flying insects), HBP(herbivores + birds + flying insects (ground-dwellers excluded)), O(herbivores + all enemies) and HPGD(herbivores + flying insects + ground-dwellers (birds excluded). 
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          For date2, Aphids population growth  was highest in H, which is followed by HGD, HP, HPGD, HBP and O.
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          For date3, aphids population growth was highest in H, this was followed by HGD, HP, HBP, O and HPGD. 
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          Overall, the treatment H, which include 
                                                                                                                                                                                                                                                                                                                                                                                                                          herbivores only (all enemies excluded), could reduce the aphids population growth most, and, aphids population growth was less in the date 3.
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          For % Seminatural habitat,  the more complex landscape is,  the higher aphids population they have, and in the sampling date3,  aphids population growth was stable, regardless  of % seminatural habitat.
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          Our plot data, effects of landscape complexity and natural enemy exclusion on average daily aphid population growth across three sampling dates (1–3), corresponds with the date from the article.
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          #Effects of treatment on Parasitism rate 
                                                                                                                                                                                                                                                                                                                                                                                                                          For parasitism rate, HPGD was highest, and which was followed by O, HBP, HP, HGD, and H at date 1.
                                                                                                                                                                                                                                                                                                                                                                                                                          At date 2, HP was highest, and which is followed by HBP, O and HPGD, HGD, and H.
                                                                                                                                                                                                                                                                                                                                                                                                                          At date 3,  HP was maximum and followed by HBP, HPGD, O HGD and H.
                                                                                                                                                                                                                                                                                                                                                                                                                          Among all, HP(herbivores + flying insects) was highest at all sampling dates.
                                                                                                                                                                                                                                                                                                                                                                                                                          In the treatment that we remove every enemies was not changed much in all sampling dates.
                                                                                                                                                                                                                                                                                                                                                                                                                          Our plot data, effects of treatment on PR, at date1 corresponded with the data from the article.
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          Our plot data, effects of landscape complexity and natural enemy exclusion on aphids parasitism rate across three sampling dates (1–3), corresponds with the date from the article.
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          #Effects of treatment on Syrphid fraction
                                                                                                                                                                                                                                                                                                                                                                                                                          O was highest  and followed by HPGD, HP, HGD, HPGD and H, and at  date 3, there was and increase of syrphid fraction in all treatments except for treatment H.
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                          Our plot data, effects of landscape complexity and natural enemy exclusion on syrphid fraction across three sampling dates (1–3), corresponds with the date from the article.
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                             #Effects of treatment on Parasitism rate 
                                                                                                                                                                                                             For parasitism rate, HPGD was highest, and which was followed by O, HBP, HP, HGD, and H at date 1.
                                                                                                                                                                                                             At date 2, HP was highest, and which is followed by HBP, O and HPGD, HGD, and H.
                                                                                                                                                                                                             At date 3,  HP was maximum and followed by HBP, HPGD, O HGD and H.
                                                                                                                                                                                                             Among all, HP(herbivores + flying insects) was highest at all sampling dates.
                                                                                                                                                                                                             In the treatment that we remove every enemies was not changed much in all sampling dates.
                                                                                                                                                                                                             Our plot data, effects of treatment on PR, at date1 corresponded with the data from the article.
                                                                                                                                                                                                             
                                                                                                                                                                                                             Our plot data, effects of landscape complexity and natural enemy exclusion on aphids parasitism rate across three sampling dates (1–3), corresponds with the date from the article.
                                                                                                                                                                                                             
                                                                                                                                                                                                             
                                                                                                                                                                                                             #Effects of treatment on Syrphid fraction
                                                                                                                                                                                                             O was highest  and followed by HPGD, HP, HGD, HPGD and H, and at  date 3, there was and increase of syrphid fraction in all treatments except for treatment H.
                                                                                                                                                                                                             
                                                                                                                                                                                                             Our plot data, effects of landscape complexity and natural enemy exclusion on syrphid fraction across three sampling dates (1–3), corresponds with the date from the article.
                                                                                                                                                                                                             